# 📊 Proyecto Final: Análisis del índice de Costo de Vida por Estado
Este proyecto tiene como objetivo realizar un EDA para entender el comportamiento y salud mental de los jóvenes en relación a su poder adquisitivo

---

## Configuración del Entorno y Librerías
Comenzamos importando las herramientas necesarias para el análisis y limpieza para posteriormente exportar y realizar la visualización en Power BI.

In [12]:
import pandas as pd
import numpy as np

In [13]:
# Cargar los datasets 
df_salud = pd.read_csv(r"H:\\Mi unidad\\BELLA\\CURSO DATA ANALYTICS\\Proyecto_Final\\data\\brfss2022.csv")
df_zillow = pd.read_csv(r"H:\\Mi unidad\\BELLA\\CURSO DATA ANALYTICS\\Proyecto_Final\\data\\ZHVI.csv") 

# Exploración del BRFSS (Buscamos la columna del estado, suele llamarse '_STATE' o 'STATE')
print("DATOS DE SALUD (BRFSS)")
print(f"Filas iniciales: {df_salud.shape[0]}") # Número de filas (registros) en el dataset de salud
print("Primeras 20 columnas:")
print(list(df_salud.columns[:20]))

# Exploración de ZILLOW (Buscamos la columna del estado, suele llamarse 'RegionName' o 'StateName')
print("\n DATOS DE VIVIENDA (ZILLOW)")
print(f"Filas iniciales: {df_zillow.shape[0]}")
print("Primeras 15 columnas:")
print(list(df_zillow.columns[:15]))

print("Así se ve el archivo por dentro:")
display(df_zillow.head())

print("Primeras 5 encuestas (filas):")
display(df_salud.head())

DATOS DE SALUD (BRFSS)
Filas iniciales: 445132
Primeras 20 columnas:
['_STATE', 'FMONTH', 'IDATE', 'IMONTH', 'IDAY', 'IYEAR', 'DISPCODE', 'SEQNO', '_PSU', 'CTELENM1', 'PVTRESD1', 'COLGHOUS', 'STATERE1', 'CELPHON1', 'LADULT1', 'COLGSEX1', 'NUMADULT', 'LANDSEX1', 'NUMMEN', 'NUMWOMEN']

 DATOS DE VIVIENDA (ZILLOW)
Filas iniciales: 314
Primeras 15 columnas:
['Unnamed: 0', 'Florida', 'California', 'Texas', 'New York', 'Virginia', 'Washington', 'Michigan', 'Colorado', 'New Jersey', 'Massachusetts', 'Connecticut', 'Utah', 'Ohio', 'Alabama']
Así se ve el archivo por dentro:

,Unnamed: 0,Florida,California,Texas,New York,Virginia,Washington,Michigan,Colorado,New Jersey,...,West Virginia,Kansas,Kentucky,South Dakota,Delaware,Wisconsin,North Dakota,Nebraska,Oklahoma,Alaska
0,2000-01-01,107549.759105,187986.834929,112895.976760,150045.977338,123684.552511,173367.823567,113899.824293,176682.186996,167343.438986,...,72317.787856,87678.600553,89439.194558,106063.481039,146615.955734,117744.489235,NaN,114189.523309,82670.964090,134147.013970
1,2000-02-01,107782.721894,188618.714792,112957.327350,150580.288409,124004.602634,173758.878834,113962.557597,177309.536197,167794.538176,...,72314.692267,87695.812028,89485.371575,105838.131182,146844.056513,117710.316247,NaN,114372.059982,82705.066072,134299.376638
2,2000-03-01,108065.119232,189471.907336,112987.083347,151094.648981,124343.930892,174157.790022,114192.228542,178002.821966,168224.966274,...,72338.067604,87797.212329,89569.388767,105522.770731,147128.062514,117842.040500,NaN,114541.237906,82864.026338,134451.659620
3,2000-04-01,108639.160386,191323.933952,113134.765000,152200.898743,124985.148445,174962.894781,114649.732163,179552.984021,169178.593471,...,72397.231969,87948.798721,89778.179177,105097.698666,147777.577805,118031.209121,NaN,114803.853379,83153.484649,134630.251965
4,2000-05-01,109258.201912,193476.635902,113230.405955,153345.471798,125604.173757,175841.616004,115324.416480,181283.233628,170150.741418,...,72512.658668,88177.301635,90055.667426,104920.856265,148518.378903,118408.615469,NaN,114937.028176,83542.272174,134899.108748

Primeras 5 encuestas (filas):

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_SMOKGRP,_LCSREC,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK2,_RFDRHV8,_FLSHOT7,_PNEUMO3,_AIDTST4
0,1.0,1.0,2032022,2,3,2022,1100.0,2022000001,2.022000e+09,1.0,...,4.0,NaN,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,2.0,2.0
1,1.0,1.0,2042022,2,4,2022,1100.0,2022000002,2.022000e+09,1.0,...,4.0,NaN,2.0,5.397605e-79,1.0,5.397605e-79,1.0,2.0,2.0,2.0
2,1.0,1.0,2022022,2,2,2022,1100.0,2022000003,2.022000e+09,1.0,...,4.0,NaN,2.0,5.397605e-79,1.0,5.397605e-79,1.0,NaN,NaN,2.0
3,1.0,1.0,2032022,2,3,2022,1100.0,2022000004,2.022000e+09,1.0,...,3.0,2.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,9.0,9.0,2.0
4,1.0,1.0,2022022,2,2,2022,1100.0,2022000005,2.022000e+09,1.0,...,4.0,NaN,1.0,1.000000e+01,1.0,1.400000e+02,1.0,NaN,NaN,2.0

In [14]:
# LIMPIEZA DE ZILLOW 
# Renombramos esa columna sin nombre a 'Fecha'
df_zillow = df_zillow.rename(columns={'Unnamed: 0': 'Fecha'})

# Derretimos para tener: Fecha | Estado | Precio_Vivienda
df_zillow_long = df_zillow.melt(id_vars=['Fecha'], var_name='StateName', value_name='Precio_Vivienda')

# Calculamos el precio promedio histórico por estado 
df_precios_estado = df_zillow_long.groupby('StateName')['Precio_Vivienda'].mean().reset_index()


# EL TRADUCTOR DE ESTADOS (Diccionario FIPS)
# Este diccionario convierte los números del gobierno a nombres que Zillow entiende
fips_dict = {
    1: 'Alabama', 2: 'Alaska', 4: 'Arizona', 5: 'Arkansas', 6: 'California', 8: 'Colorado', 
    9: 'Connecticut', 10: 'Delaware', 11: 'District of Columbia', 12: 'Florida', 13: 'Georgia', 
    15: 'Hawaii', 16: 'Idaho', 17: 'Illinois', 18: 'Indiana', 19: 'Iowa', 20: 'Kansas', 
    21: 'Kentucky', 22: 'Louisiana', 23: 'Maine', 24: 'Maryland', 25: 'Massachusetts', 
    26: 'Michigan', 27: 'Minnesota', 28: 'Mississippi', 29: 'Missouri', 30: 'Montana', 
    31: 'Nebraska', 32: 'Nevada', 33: 'New Hampshire', 34: 'New Jersey', 35: 'New Mexico', 
    36: 'New York', 37: 'North Carolina', 38: 'North Dakota', 39: 'Ohio', 40: 'Oklahoma', 
    41: 'Oregon', 42: 'Pennsylvania', 44: 'Rhode Island', 45: 'South Carolina', 46: 'South Dakota', 
    47: 'Tennessee', 48: 'Texas', 49: 'Utah', 50: 'Vermont', 51: 'Virginia', 53: 'Washington', 
    54: 'West Virginia', 55: 'Wisconsin', 56: 'Wyoming'
}

# Creamos una nueva columna en salud con el nombre real
df_salud['StateName'] = df_salud['_STATE'].map(fips_dict)

# LA GRAN UNIÓN
# Cruzamos las 445k filas de salud con los 50 precios de Zillow
df_final = pd.merge(df_salud, df_precios_estado, on='StateName', how='inner')

print(f"✅ ¡Fusión exitosa! Tienes {df_final.shape[0]} filas listas para analizar.")
print(f"Y tienes {df_final.shape[1]} columnas.")

C:\Users\usuario\AppData\Local\Temp\ipykernel_5688\290180246.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_salud['StateName'] = df_salud['_STATE'].map(fips_dict)

✅ ¡Fusión exitosa! Tienes 432589 filas listas para analizar.
Y tienes 328 columnas.

In [15]:
# Definimos las columnas "estrella" para el análisis 

columnas_finales = [
    'StateName',        # El estado (Tu ancla geográfica)
    'Precio_Vivienda',  # Costo de vida (Tu dato estrella de Zillow)
    'MENTHLTH',         # Días con mala salud mental en el mes (Tu métrica de "Felicidad/Estrés")
    'PHYSHLTH',         # Días con mala salud física
    'EMPLOY1',          # Situación laboral (Empleado, desempleado, tiempo parcial...)
    'INCOME3',          # Nivel de ingresos familiares
    'MARITAL',          # Estado civil
    'EDUCA',            # Nivel educativo
    '_AGEG5YR',         # Grupo de edad
    'SEXVAR',           # Género
    'SLEPTIM1',         # Horas de sueño al día
    'EXERANY2',         # ¿Hizo ejercicio este mes?
    'HLTHPLN1',         # ¿Tiene seguro médico?
    '_BMI5CAT',         # Categoría de Índice de Masa Corporal
    'SMOKE100',         # Historial de tabaquismo (Factor de estrés/salud)
    'DRNKANY6',         # Consumo de alcohol reciente
    '_RACE',            # Raza / Etnia
    'VETERAN3',         # Estatus de Veterano
    'DIFFWALK',         # Dificultad para caminar (Indicador de discapacidad)
    'DIABETE4',         # Diagnóstico de diabetes (Enfermedad crónica)
    'ASTHMA3',          # Diagnóstico de asma
    'RENTHOM1'          # ¿Alquila o es dueño de su casa? 
    'IMONTH',           # Mes en que se hizo la encuesta
    'IYEAR'             # Año de la encuesta
]

# Filtrado Seguro
# Usamos una lista de comprensión para evitar errores si algún código cambió levemente
columnas_existentes = [col for col in columnas_finales if col in df_final.columns]

# Creamos nuestro DataFrame definitivo blindado con .copy()
df_powerbi = df_final[columnas_existentes].copy()

# Verificamos la rúbrica por última vez
print("DATASET DEFINITIVO PARA POWER BI")
print(f"✅ FILAS TOTALES: {df_powerbi.shape[0]}")
print(f"✅ COLUMNAS TOTALES: {df_powerbi.shape[1]}")

# EL GRAN EXPORT (Guardamos el archivo final)
df_powerbi.to_csv('dataset_powerbi_salud_vivienda.csv', index=False)
print("\n🎉 ¡Archivo 'dataset_powerbi_salud_vivienda.csv' guardado y listo!")

DATASET DEFINITIVO PARA POWER BI
✅ FILAS TOTALES: 432589
✅ COLUMNAS TOTALES: 20

🎉 ¡Archivo 'dataset_powerbi_salud_vivienda.csv' guardado y listo!